name: CI

on: [push, pull_request]

jobs:
  Server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'api-rest-covid'
          heroku_email: 'cobogue@gmail.com'
          appdir: "server"


  Client:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: client

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: npm packages cache
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install Packages and Build
          run: |
            npm install
            npm run-script build

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          uses: netlify/actions/cli@master
          env:
            CBD_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
            NETLIFY_SITE_ID: c1043f0a-044d-4f66-88dd-18741dc5c44f
          with:
            args: deploy --dir=client/build --prod

        